---
- name: Correct OS Defaults
- include: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Correct OS Defaults
- include: windows.yml
  when: ansible_facts['os_family']|lower == 'windows'